- id: '1745929919264'
  alias: EVENT_START
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_kavo_tc_2
    event: start
    offset: 0:0:0
  conditions: []
  actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: EVENT START TRIGGERED!!!!
      title: START
  mode: parallel
- id: '1745931830069'
  alias: EVENT_START_SHELLY_ON
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_kavo_tc_2
    event: start
    offset: -0:1:0
  conditions: []
  actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: Hygiene plan Started
  - type: turn_on
    device_id: 528fc99fc3d656eee6397569e0abdc7e
    entity_id: 21228baf9af600a63edb8b294855473b
    domain: switch
  mode: parallel
- id: '1747312193633'
  alias: Abends/Wöchentlich turn off
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.kavo_tc_2_hygiene_plan_phase
    from:
    to: Evening Hygiene process completed
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - trigger: state
    entity_id:
    - sensor.kavo_tc_2_hygiene_plan_phase
    from:
    to: Weekly Hygiene process completed
    for:
      hours: 0
      minutes: 0
      seconds: 10
  conditions: []
  actions:
  - type: turn_off
    device_id: 528fc99fc3d656eee6397569e0abdc7e
    entity_id: 21228baf9af600a63edb8b294855473b
    domain: switch
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: Abends/Wöchentlich Done!
  mode: parallel
