- id: '1745929919264'
  alias: EVENT_START
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_test_chair_02
    event: start
    offset: 0:0:0
  conditions: []
  actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: EVENT START TRIGGERED!!!!
      title: START
  mode: parallel
- id: '1745929978201'
  alias: EVENT END
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_test_chair_02
    event: end
    offset: 0:0:0
  conditions: []
  actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: EVENT END!!!
      title: END
  mode: parallel
- id: '1745931830069'
  alias: EVENT_START_SHELLY_ON
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_test_chair_02
    event: start
    offset: -0:1:0
  conditions: []
  actions:
  - type: turn_on
    device_id: 528fc99fc3d656eee6397569e0abdc7e
    entity_id: 21228baf9af600a63edb8b294855473b
    domain: switch
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: Hygiene plan Started
  mode: parallel
- id: '1745931943309'
  alias: EVENT_END_SHELLY_OFF
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_test_chair_02
    event: end
    offset: 0:0:0
  conditions: []
  actions:
  - type: turn_off
    device_id: 528fc99fc3d656eee6397569e0abdc7e
    entity_id: 21228baf9af600a63edb8b294855473b
    domain: switch
  mode: parallel
- id: '1746514868348'
  alias: Evening/intense stop
  description: ''
  triggers:
  - trigger: calendar
    entity_id: calendar.hygiene_plan_test_chair_02
    event: end
    offset: 0:0:0
  conditions:
  - condition: template
    value_template: "{{ 'evening' in trigger.calendar_event.description|lower or\n
      \  'intense' in trigger.calendar_event.description|lower }}\n"
  - condition: state
    entity_id: sensor.test_chair_02_hygiene_plan_phase
    state: Hygiene process completed
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - condition: template
    value_template: '{% set completed_at = states(''sensor.test_chair_02_hygiene_plan_done_at'')
      %}

      {{ completed_at != ''unknown'' and as_timestamp(now()) - as_timestamp(completed_at)
      < 600 }}'
  actions:
  - type: turn_off
    device_id: 528fc99fc3d656eee6397569e0abdc7e
    entity_id: 21228baf9af600a63edb8b294855473b
    domain: switch
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: evening/intense done!
  mode: parallel
